# Generated by Django 6.0.6 on 2026-06-12 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                (
                    "password",
                    models.CharField(db_column="password_hash", max_length=128),
                ),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Hadith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kitab", models.CharField(max_length=100)),
                ("nomor", models.CharField(max_length=50)),
                ("bab", models.CharField(blank=True, max_length=255, null=True)),
                ("arab", models.TextField(blank=True, null=True)),
                ("terjemahan", models.TextField(blank=True, null=True)),
                ("english", models.TextField(blank=True, null=True)),
                ("sanad_json", models.TextField(blank=True, default="[]", null=True)),
                (
                    "sanad_edges_json",
                    models.TextField(blank=True, default="[]", null=True),
                ),
                (
                    "narators_id_json",
                    models.TextField(
                        blank=True, db_column="narators_id", default="[]", null=True
                    ),
                ),
            ],
            options={
                "db_table": "hadiths",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SubTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "sub_themes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tema", models.CharField(max_length=255)),
                ("deskripsi", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "themes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ThematicHadith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("syarh_hadith", models.TextField(blank=True, null=True)),
                (
                    "hadith",
                    models.ForeignKey(
                        db_column="hadith_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thematic_entries",
                        to="api.hadith",
                    ),
                ),
                (
                    "sub_theme",
                    models.ForeignKey(
                        db_column="sub_theme_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hadiths",
                        to="api.subtheme",
                    ),
                ),
            ],
            options={
                "db_table": "tematik",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="subtheme",
            name="theme",
            field=models.ForeignKey(
                db_column="theme_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_themes",
                to="api.theme",
            ),
        ),
    ]
