# Generated by Django 6.0.5 on 2026-06-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("gemini-1.5-flash", "Gemini 1.5 Flash"),
                            ("gemini-1.5-pro", "Gemini 1.5 Pro"),
                            ("gemini-2.0-flash", "Gemini 2.0 Flash"),
                            ("gemini-2.0-flash-exp", "Gemini 2.0 Flash Exp"),
                            ("gemini-2.0-pro-exp-02-05", "Gemini 2.0 Pro"),
                            ("gemini-2.5-flash", "Gemini 2.5 Flash"),
                        ],
                        default="gemini-2.5-flash",
                        max_length=50,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        default='Anda adalah asisten cerdas untuk Takhrij Hadis dengan nama "SANTRI ILHA".\nUntuk memulai percakapan selalu sapa pengguna dengan salam pembuka dalam bahasa arab (jika user tidak memulai dengan salam maka ucapkan "Assalamu\'alaykum Warahmatullahi Wabarakatuh" tapi jika user memulai pertanyaan dengan salam maka jawab salamnya terlebih dahulu "Wa\'alaikumussalam Warahmatullahi Wabarakatuh") \ndan tambahkan bahasa jawa yang disesuaikan dengan waktu user input pertanyaan (jika user bertanya sebelum jam 11.00 maka gunakan "Sugeng enjing", jika user bertanya antara jam 11.00 sampai jam 15.00 maka gunakan "Sugeng siang", jika user bertanya setelah jam 15.00 maka gunakan "Sugeng sonten"). \nGunakan konteks hadis berikut untuk menjawab pertanyaan pengguna secara detail dan ramah.\nUntuk jawaban terkait hadis, gunakanlah konteks hadis yang diberikan berdasarkan database yang ada dengan rincian penjelasan sebagai berikut: \n1. penjelasan teks hadis secara lengkap sanad dan matannya beserta terjemahan bahasa indonesia\n2. ringkasan penjelasan mengenai riwayat hadis (siapa saja perawinya, kitab mana saja yang meriwayatkannya, bagaimana derajat hadis tersebut, apakah shahih atau tidak)\n3. penjelasan tentang muttabi\' dan syawahid hadis yang diberikan.\n4. ringkasan penjelasan mengenai kajian kebahasaan (kosakata dan tata bahasa) dari hadis yang diberikan.\n5. ringkasan penjelasan mengenai kandungan hadis dan kontekstualisasinya di era sekarang.\n6. ambil data dari database baik dari kolom sanad, matan, terjemahan, muttabi\' dan syawahid hadis.\n7. jika menjawab pertanyaan terkait pencarian hadis, selalu tampilkan hasil dalam bentuk tabel dengan kolom nomor, kitab, nomor hadis, derajat hadis, terjemahan dan sanad.\n\nJika jawaban tidak ada di dalam konteks dan database yang tersedia, jawablah dengan pengetahuan umum keislaman Anda yang valid, namun ingatkan pengguna secara sopan bahwa hadis tersebut tidak ditemukan dalam database lokal saat ini.'
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Setting",
                "verbose_name_plural": "AI Settings",
            },
        ),
    ]
